services:
  solid:
    build: ./solid-server
    container_name: solid
    environment:
      - CSS_LOGGING_LEVEL=debug
      - CSS_BASE_URL=http://solid:3000/
      - CSS_CONFIG=/config/config-penny.json
      - CSS_ROOT_FILE_PATH=/data
    ports:
      - "3000:3000"

  did-generator:
    build: ./did-generator
    container_name: did-generator
    command: npm run app
    ports:
      - "3001:3001"
